FROM lopsided/archlinux
LABEL maintainer="Robin Cole @robmarkcole"

EXPOSE 8501

COPY requirements.txt .
RUN pacman --noconfirm -Syu
RUN pacman --noconfirm -S cmake gcc python python-pip python-setuptools git util-linux sudo
RUN pip install -r requirements.txt

RUN mkdir -p /app
COPY app /app
WORKDIR /app

ENTRYPOINT [ "streamlit", "run"]
CMD ["deepstack-ui.py"]
