BOX = "box"
FILE = "file"
OBJECT = "object"

# rgb(red, green, blue)
RED = (255, 0, 0)  # For objects within the ROI
GREEN = (0, 255, 0)  # For ROI box
YELLOW = (255, 255, 0)  # For objects outside the ROI

DEFAULT_CLASSES = [
    "bicycle",
    "bus",
    "car",
    "cat",
    "dog",
    "motorcycle",
    "person",
    "truck",
]

CLASSES = [
    "airplane",
    "apple",
    "backpack",
    "banana",
    "baseball bat",
    "baseball glove",
    "bear",
    "bed",
    "bench",
    "bicycle",
    "bird",
    "boat",
    "book",
    "bottle",
    "bowl",
    "broccoli",
    "bus",
    "cake",
    "car",
    "carrot",
    "cat",
    "cell phone",
    "chair",
    "clock",
    "couch",
    "cow",
    "cup",
    "dining table",
    "dog",
    "donot",
    "elephant",
    "fire hydrant",
    "fork",
    "frisbee",
    "giraffe",
    "hair dryer",
    "handbag",
    "horse",
    "hot dog",
    "keyboard",
    "kite",
    "knife",
    "laptop",
    "microwave",
    "motorcycle",
    "mouse",
    "orange",
    "oven",
    "parking meter",
    "person",
    "pizza",
    "potted plant",
    "refrigerator",
    "remote",
    "sandwich",
    "scissors",
    "sheep",
    "sink",
    "skateboard",
    "skis",
    "snowboard",
    "spoon",
    "sports ball",
    "stop_sign",
    "suitcase",
    "surfboard",
    "teddy bear",
    "tennis racket",
    "tie",
    "toaster",
    "toilet",
    "toothbrush",
    "traffic light",
    "train",
    "truck",
    "tv",
    "umbrella",
    "vase",
    "wine glass",
    "zebra",
]
